kramdown:
  input: GFM
  hard_wrap: false
project: "JLang"
contact: jlang-users-l@cornell.edu
contact-join: jlang-users-l-request@cornell.edu

github:
  url: https://github.com/polyglot-compiler/JLang

